<%@page contentType="text/html" pageEncoding="UTF-8"%>
<div class="container">
    <!-- Breadcrumbs -->
    <ol class="breadcrumb" style="margin-top: 20px;">
        <li class="breadcrumb-item">
            <a href="home/trang-chu.html">Trang chủ</a>
        </li>
        <li class="breadcrumb-item active">Điều khoản - điều kiện</li>
    </ol>

    <div class="row" style="margin-bottom: 30px;">
        <!-- Thông tin điều khoản - điều kiện -->
        <div class="col-lg-12" style="margin-top: 20px;">
            <a class="ft-logo" href="index.html"><img src="files/home/logogioithieu.png"></a>
            <hr>
	            <div style="">
					<div>
					<h2 class="a14 green" style="font-size: 19pt;"><span id="ctl00_MainContent_lblPageTitle" style="font-size:16pt">Điều khoản, điều kiện và thông báo của Camnangdulich</span></h2>
					
					</div>
					<div style="padding-top: 20px;" class="post-body">
					<span id="ctl00_MainContent_lblPageContent"><p>Chào mừng quý khách đến Camnangdulich.com. Website được cung cấp chỉ để hỗ trợ khách hàng trong việc thu thập các thông tin du lịch, thông tin lưu trú và các dịch vụ liên quan đến du lịch, thực hiện việc đặt chỗ và các giao dịch hợp pháp khác với nhà cung cấp dịch vụ du lịch, lưu trú.</p>
					<p>Điều khoản và điều kiện sử dụng dưới đây được áp dụng cho các dịch vụ của chúng tôi. Bằng việc truy cập hoặc sử dụng website này theo bất cứ cách thức nào, quý khách đồng ý ràng buộc bởi điều khoản sử dụng. Trong phạm vi quý khách đặt bất kỳ sản phẩm nào hoặc dịch vụ du lịch nào trên website này hoặc thông qua tổng đài điện thoại của chúng tôi, quý khách đồng ý rằng điều khoản và điều kiện sử dụng được áp dụng cho tất cả các giao dịch. Vui lòng đọc kỹ điều khoản và điều kiện sử dụng. Các điều khoản và điều kiện quy định, các chính sách được gọi chung là “ điều khoản sử dụng”. Quý khách vui lòng đọc kỹ điều khoản sử dụng. Nếu quý khách không chấp thuận tất cả các điều khoản vui lòng không sử dụng website này hoặc thực hiện việc đặt chỗ thông qua website này hoặc đặt chỗ qua tổng tài điện thoại của chúng tôi. Điều khoản sử dụng có thể thay đổi theo thời gian mà chúng tôi không cần thông báo trước và việc quý khách tiếp tục truy cập hoặc sử dụng website này thể hiện sự chấp thuận của quý khách đối với điều khoản sử dụng được cập nhật hoặc sửa đối.</p>
					<p><strong>1. Sử dụng website</strong></p>
					<p>Quý khách phải đảm bảo rằng quý khách đã đủ 18 tuổi, quý khách có thẩm quyền hợp pháp và có nghĩa vụ ràng buộc về pháp lý. Quý khách sử dụng website này là phù hợp với điều khoản sử dụng này. Quý khách sẽ chỉ sử dụng website này để thực hiện việc đặt chỗ hợp pháp cho quý khách hoặc cho người khác mà quý khách có sự cho phép hợp pháp để thực hiện. Tất cả các thông tin do quý khách cung cấp trên website này là trung thực, chính xác, hiện thời và hoàn chỉnh. Và nếu quý khách có tài khoản trên Camnangdulich.com, quý khách sẽ bảo vệ thông tin tài khoản của quý khách, sẽ giám sát và chiệu trách nhiệm hoàn toàn đối với bất cứ việc sử dụng nào đối với tài khoản của quý khách bởi quý khách hoặc bất cứ người nào không phải là quý khách. Chúng tôi có quyền không chấp nhận khách hàng sử dụng dịch vụ tùy theo quyết định riêng của chúng tôi mà không phải biện minh cho việc từ chối đó. Lý do điển hình để từ chối một khách hàng đặt phòng: khách sạn yêu cầu, vi phạm điều khoản sử dụng, nghi ngờ gian lận, trộm cắp, nghi ngờ hoạt động tội phạm, đặt nghi ngờ do khách hàng cung cấp thông tin sai lệch, sai sót, vấn đề về thẻ tín dụng, danh sách đen của chính phủ…</p>
					<p>Nội dung và thông tin trên website này cũng như hạ tầng cơ sở được sử dụng để cung cấp nội dung và thông tin đó là tài sản thuộc về chúng tôi hoặc các bên cung cấp hàng hóa, dịch vụ của chúng tôi. Theo đó, như là một điều kiện của việc sử dụng các trang web, quý khách đồng ý không sử dụng trang web hoặc nội dung, thông tin của website cho bất kỳ mục đích thương mại hoặc phi cá nhân (trực tiếp hoặc gián tiếp) hoặc cho bất kỳ mục đích bất hợp pháp, trái pháp luật hoặc bị cấm bởi các Điều khoản sử dụng. Trừ trường hợp được chấp thuận trước bằng văn bản của chúng tôi, bạn đồng ý không sửa đổi, sao chép, phân phối, truyền tải, hiển thị, tái sản xuất, xuất bản, tạo ra tác phẩm phái sinh, chuyển nhượng, hoặc bán lại bất kỳ thông tin, phần mềm, sản phẩm, hoặc dịch vụ thu được từ trang web.</p>
					<p><strong>2. Về xếp hạng sao của khách sạn</strong></p>
					<p>Mức xếp hạng theo sao của khách sạn được đưa ra dựa trên thông tin mà chúng tôi tiếp nhận từ phía khách sạn, nhằm mục đích cung cấp thêm cho việc tham khảo đơn thuần của khách hàng . Camnangdulich&nbsp; không tự kiểm tra cũng như xác nhận những thông tin liên quan đến xếp hạng sao là hoàn toàn chính xác so với thực tế .</p>
					<p>Qua đây chúng tôi từ chối đưa ra bất cứ tuyên bố hay cam kết nào liên quan đến chất lượng hoặc tính thỏa đáng của bất kỳ khách sạn nào được đề cập trên trang web .</p>
					<p>Mức xếp hạng sao chỉ biểu thị mức độ tiện nghi mà khách có thể kỳ vọng ở một khách sạn cụ thể. Chúng tôi lưu ý đến bạn rằng các mức xếp hạng sao có thể khác nhau tùy thuộc vào vị trí, điều kiện thị trường, kinh tế hoặc thông lệ … của từng địa phương . Từ đó có thể thấy ở một mức xếp hạng sao tại quốc gia/thành phố này không thể so sánh với cùng một mức xếp hạng sao tại quốc gia/thành phố khác .</p>
					<p>Các mức xếp hạng theo sao không nhất thiết phản ánh tất cả các tiện nghi hay dịch vụ có thể có sẵn tại khách sạn. Một số tiện nghi có thể không có sẵn trong mỗi hoặc tất cả các phòng với cùng một mức xếp hạng sao cụ thể . Xin vui lòng liên hệ với dịch vụ khách hàng của chúng tôi để kiểm tra về tình trạng phòng có thể đáp ứng được các tiện nghi cụ thể mà bạn yêu cầu hoặc cảm thấy quan trọng .</p>
					<p>Cuối cùng, Camnangdulich khuyến nghị bạn không nên hoàn toàn dựa vào xếp hạng sao để làm căn cứ lựa chọn khách sạn và đi đến quyết định đặt phòng tại khách sạn nào đó.</p>
					<p><strong>3.&nbsp;Chính sách giá và sự đảm bảo về giá</strong></p>
					<p>Chúng tôi cố gắng để có mức giá cạnh tranh và chúng tôi muốn quý khách trả mức giá thấp có thể cho kỳ nghỉ của quý khách tại một Khách sạn. Điều này có nghĩa rằng vào thời điểm quý khách thanh toán đặt phòng cho chúng tôi, chúng tôi đảm bảo rằng giá phòng của chúng tôi là hợp lý và cạnh tranh.</p>
					<p>Xin lưu ý, gía phòng trên website có tính hiện thời và giá cho đặt phòng của quý khách được chốt&nbsp; vào lúc mà quý khách tiến hành thanh toán cho chúng tôi.</p>
					<p>Gía phòng trên website có thể thay đổi tùy theo các điều kiện đặc biệt như điều kiện hủy đổi hay tùy thuộc vào các chương trình ưu đãi đặc biệt của chúng tôi cũng như của đơn vị khách sạn cung cấp phòng cho chúng tôi tại mỗi thời điểm. Chúng tôi không điều chỉnh giá mới cho các đặt phòng đã thành công trước đó. Gía đặt phòng của quý khách sẽ theo giá vào thời điểm mà quý khách thanh toán cho chúng tôi.</p>
					<p>Đối với các đặt phòng quốc tế, Camnangdulich sử dụng hệ thống đặt phòng online. Do đó, giá và tình trạng phòng trống mang tính thời điểm, và có thể thay đổi liên tục tùy thuộc vào việc truy cập hay việc đặt phòng của các khách hàng online khác. Gía và tình trạng phòng quốc tế chỉ được xác nhận lần cuối cùng khi chúng tôi hoàn tất đặt phòng và gửi lại Hotel Voucher cho quý khách. Trước khi đặt phòng quốc tế của quý khách hoàn tất, chúng tôi không thể đảm bảo về giá và phòng trống. Trách nhiệm của chúng tôi nằm ở chỗ hỗ trợ quý khách đặt phòng và sẽ thông báo lại khi khách sạn có sự điều chỉnh về giá.</p>
					<p><strong>4. Xác nhận thông tin đặt phòng:</strong></p>
					<p>Đặt phòng của quý khách, chỉ được xác nhận khi có sự xác nhận từ nhân viên CSKH của chúng tôi.</p>
					<p>Chúng tôi sẽ gửi thông tin về giá, tình trạng phòng trống, chính sách hủy đổi và những ưu đãi kèm theo của các chương trình khuyến mãi liên quan đến đặt phòng của quý khách trong các email yêu cầu thanh toán. Qúy khách vui lòng kiểm tra kỹ thông tin trước khi quyết định thanh toán. Xin lưu ý những nội dung này chỉ được xác nhận trong khoảng thời gian chúng tôi thông báo. Đặt phòng của quý khách có thể bị hủy hoặc những nội dung liên quan có thể không còn hiệu lực nếu quý khách thanh toán không đúng hạn yêu cầu.</p>
					<p>Hotel Voucher – Phiếu xác nhận dịch vụ du lịch mà chúng tôi gửi cho quý khách sau khi quý khách thanh toán là xác nhận cuối cùng về toàn bộ nội dung đặt phòng của quý khách với chúng tôi. Xin quý khách vui lòng đọc kỹ những thông tin trong Hotel Voucher.&nbsp; Chúng tôi không thể và không chịu trách nhiệm, nếu thiệt hại hoặc sai sót xảy ra do quý khách không đọc và nắm rõ những thông tin mà chúng tôi đã gửi trong Hotel Voucher. Chúng tôi cũng không thể chắc chắn và đảm bảo các yêu cầu đặc biệt của quý khách được thực hiện cho đến khi chúng tôi gửi email Phiếu xác nhận dịch vụ cho quý khách. Do vậy, hãy chắc chắn quý khách đã nắm và kiểm tra kỹ những nội dung chúng tôi xác nhận trong Hotel Voucher.</p>
					<p><strong>5.&nbsp;Chính sách hủy/ đổi đặt phòng &amp; NoShow</strong></p>
					<p>Nếu quý khách muốn thay đổi thông tin đặt phòng, vui lòng liên hệ <strong>Bộ Phận Chăm Sóc Khách Hàng</strong> của chúng tôi qua số điện thoại <strong>08 39251055</strong>.&nbsp; Chúng tôi sẽ cố gắng để hỗ trợ quý khách. Tuy nhiên, chúng tôi không đảm bảo mọi yêu cầu sẽ được thực hiện.&nbsp;</p>
					<p>Cùng một khách sạn, có thể có nhiều chính sách hủy đổi khác nhau. Sự khác nhau này nằm ở những ràng buộc của giá và những ưu đãi của chương trình khuyến mãi mà quý vị lựa chọn khi thực hiện đặt phòng. Do đó, xin vui lòng xem kỹ chính sách hủy/ đổi đặt phòng của quý khách trong email xác nhận đặt phòng mà chúng tôi gửi cho quý khách.&nbsp;</p>
					<p>Tất cả các yêu cầu hủy đổi của quý khách sẽ được giải quyết dựa vào chính sách hủy đổi của đặt phòng của khách sạn mà chúng tôi đã gửi cho quý khách. Phí hủy đặt phòng sẽ được áp dụng nếu đặt phòng của quý khách là không được phép hủy/ đổi hoặc thời điểm gửi yêu cầu hủy phòng của quý khách đã rơi vào quy định phạt hủy. Xin quý khách vui lòng kiểm tra kỹ chính sách hủy đổi trước khi gửi yêu cầu hủy/ đổi cho chúng tôi.</p>
					<p>Việc đến khách sạn muộn hơn so với lịch trình đã đặt mà không có sự thông báo trước sẽ bị xem là Noshow và khách sạn có thể xem đây như là yêu cầu hủy phòng&nbsp; cận và áp dụng chính sách hủy đối với đặt phòng của quý khách (hủy phòng vào ngày check in).</p>
					<p>Ngoài ra, với tất cả các đơn đặt phòng được phép hủy đổi. Chúng tôi sẽ tính phí dịch vụ của Camnangdulich khi quý vị yêu cầu hủy/ đổi đặt phòng.</p>
					<p><strong>6. Thanh Toán</strong></p>
					<p>Quý khách thanh toán tiền đặt phòng theo một trong 4 cách sau :</p>
					<p>-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Thanh toán tiền mặt tại văn phòng Camnangdulich : Tầng 12, 242 Cống Quỳnh – Quận 1</p>
					<p>-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Camnangdulich thu tiền : Tại các quận trung tâm ở TPHCM và Hà Nội theo địa chỉ mà quý khách yêu cầu miễn phí , sẽ tính phí nếu quý khách yêu cầu thu tại các quận huyện ngoại thành hoặc xa trung tâm thành phố</p>
					<p>Qui định về mức phí thu tiền tại địa chỉ của khách hàng như sau :<br> Quận 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, Bình Thạnh, Tân Bình, Phú Nhuận: Miễn phí<br> Quận Tân Phú, Gò Vấp: phí 30.000 vnđ (miễn phí cho đặt phòng trên 20 triệu)<br> Quận 12, Thủ Đức, Bình Tân: phí 50.000 vnđ (miễn phí cho đặt phòng trên 20 triệu)<br> Quận 9, Bình Chánh: xin vui lòng liên hệ cskh để được sắp xếp cụ thể về thời gian và mức phí.</p>
					<p>-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Thanh toán qua chuyển khoản ngân hàng</p>
					<p>-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Thanh toán thẻ tín dụng : chỉ áp dụng đối với một số khách sạn hoặc một số mức giá. Những chương trình khuyến mãi và những mức giá cạnh tranh Camnangdulich không áp dụng thanh toán thẻ. Chi tiết cụ thể vui lòng liên hệ với Camnangdulich khi đặt phòng. Để hạn chế việc sử dụng thẻ tín dụng giả mạo, Chúng tôi có thể yêu cầu quý khách bổ sung giấy bổ sung giấy CMND hoặc hộ chiếu (passport) khi đặt phòng để xác nhận chủ thẻ. Một bản lưu của thẻ tín dụng / CMND hoặc hộ chiếu (passport) của Quý Khách cũng có thể được nhà cung cấp phòng giữ lại với mục đích loại trừ thẻ giả mạo, xác nhận nơi cấp thẻ tín dụng, trong trường hợp xảy ra sự cố.</p>
					<p><strong>7. Thông tin website:</strong></p>
					<p>Chúng tôi nổ lực cam kết tất cả thông tin chính xác sẽ được hiển thị trên trang web. Tuy nhiên thông tin về khách sạn trên trang web được dựa trên các thông tin do các nhà cung cấp của chúng tôi gửi cho chúng tôi. Do đó, chúng tôi không thể đảm bảo được rằng mọi thông tin là đầy đủ, chính xác hoàn toàn hoặc không có bất kỳ lỗi nào, và chúng tôi không phải chịu trách nhiệm đối với bất cứ mọi sai sót, thông tin không chính xác, sai lệnh, không trung thực hoặc không cung cấp thông tin. Chúng tôi bảo lưu quyền thay đổi thông tin hiển thị trên trang web (bao gồm Điều khoản và Điều kiện này) bất kỳ thời điểm nào mà không phải báo trước. Trường hợp có vấn đề xảy ra, chúng tôi sẽ nổ lực liên hệ giữa khách sạn và khách hàng đưa ra hướng xử lý tốt có thể trong phạm vi dịch vụ của chúng tôi<br><br>Trang web không giới thiệu hay xác nhận về sao, chất lượng, tiêu chuẩn, mức độ dịch vụ,… của bất kỳ khách sạn nào được đăng trang web. Do đó, chúng tôi từ chối việc đưa ra bất kỳ đảm bảo hoặc cam kêt nào liên quan đến việc giới thiệu hay xác nhận trên. Các khách sạn trên trang web có thể được xếp hạng theo các tiêu chuẩn khác nhau, bao gồm nhưng không giới hạn theo sao, theo đánh giá chủ quan của đa số khách hàng, theo đánh giá dựa trên tiêu chí, đặc tính của từng vùng miền,… và có thể được cập nhật hoặc được sửa đổi tại từng thời điểm. Các thông tin xếp hạng khách sạn trên trang web chỉ nhằm mục đích hướng dẫn chung, không đảm bảo tính chính xác của các xếp hạng<br><br>Những ý kiến, đánh giá và góp ý về các khách sạn được đăng trên trang web hoàn toàn là do những khách hàng đã sử dụng dịch vụ của các khách sạn đó cung cấp cho chúng tôi, và chỉ nhằm một mục đích là thông tin tham khảo cho những khách hàng khác để chọn lựa được một khách sạn phù hợp với nhu cầu lưu trú của họ. Bằng việc gửi cho Camnangdulich bài đánh giá của bạn, bạn đã hoàn toàn đồng ý cấp cho Camnangdulich quyền sử dụng và sở hữu bài đánh giá của bạn. Camnangdulich bảo lưu quyền hiệu chỉnh, phiên dịch, từ chối đăng tải hoặc xóa các bài đánh giá theo quyết định của mình mà không cần thông báo.<br><br>Chuyên trang Thư Viện Du lịch của Camnangdulich là trang cung cấp thông tin du lịch, ẩm thực, chia sẻ kinh nghiệm, giới thiệu địa danh,v.v.. hoàn toàn không có mục đích thương mại. Camnangdulich sử dụng thông tin các bài viết về du lịch để làm cẩm nang du lịch gửi tới các bạn.<br><br>Trang Thư Viện Du lịch đóng vai trò như người hướng dẫn thụ động cho sự cung cấp và công khai trực tuyến thông tin du lịch được các thành viên cung cấp và không có trách nhiệm hiển thị những nội dung do thành viên sử dụng đăng tải. Cộng tác viên là người chịu hoàn toàn trách nhiệm trong việc sử dụng, khai thác, cung cấp thông tin các bài viết, tin du lịch này.</p>
					<p><strong>8. Trách nhiệm :</strong></p>
					<p><strong><em>Phạm vi dịch vụ và trách nhiệm:</em></strong></p>
					<p>Camnangdulich không phải là đơn vị đại diện, sở hữu, quản lý, điều hành, kiểm soát hoặc đảm bảo cho bất kỳ sản phẩm phòng ở, khách sạn hay dịch vụ nào trên trang web hoặc các trang kết nối. Ở đây trách nhiệm của Camnangdulich chỉ cho phép thực hiện việc đặt phòng. Chúng tôi cam kết cho thuê phòng còn trống được cung cấp bởi các khách sạn thành viên, và không cho bán số phòng nhiều hơn số phòng chúng tôi có (chúng tôi không chịu trách nhiệm với lý do không có phòng trống vì khách sạn đã cho thuê vượt quá số phòng). Các khách sạn có trách nhiệm cung cấp chỗ ăn ở và đón tiếp những khách hàng đã đặt phòng thông qua Camnangdulich theo đúng nội dung đã thỏa thuận trong phiếu xác nhận đặt phòng</p>
					<p>Camnangdulich nổ lực hết mình để đảm bảo tất các mức giá hoặc thông tin hiển thị trên trang web là chính xác vào thời điểm phát hành.Tuy nhiên, các thay đổi về điều kiện kinh tế, thiên nhiên có thể xảy ra sau ngày phát hành làm các thông tin hiển thị trên trang web không còn chính xác hoặc không còn phản ánh tình trạng hiện thời. Camnangdulich bảo lưu quyền từ chối mọi đảm bảo hoặc trách nhiệm liên quan đến tính chính xác, đầy đủ, hoàn thiện hoặc sự phù hợp của tất cả nội dung đăng tải trên trang web</p>
					<p><strong><em>Miễn trừ trách nhiệm:</em></strong></p>
					<p>Các thông tin, sản phẩm, phần mềm, dịch vụ trên trang web có thể bao gồm lỗi hoặc không hoàn thiện hoặc không chính xác. Camnangdulich không đảm bảo tính chính xác và miễn trừ mọi trách nhiệm pháp lý cho bất kỳ lỗi hay tính không chính xác nào liên quan đến thông tin về sản phẩm phòng ở, khách sạn và các dịch vụ khác trên trang web.</p>
					<p>Các khách sạn và các nhà cung cấp dịch vụ dụ lịch khác trên trang web là các đơn vị độc lập, không phải là đại lý, chi nhánh hay đơn vị trực thuộc của Camnangdulich. Camnangdulich không chịu trách nhiệm cho các lỗi, sai sót, vi phạm hoặc sơ suất của bất kỳ nhà cung cấp hoặc khách sạn nào.</p>
					<p>Các thông tin xếp hạng khách sạn trên trang web chỉ nhằm mục đích hướng dẫn chung, là tài liệu tham khảo cho khách hàng trong việc chọn lựa sản phẩm dịch vụ phù hợp, Camnangdulich không đảm bảo về tính chính xác của các xếp hạng. Camnangdulich từ chối mọi tuyên bố, bảo đảm hoặc trách nhiệm liên quan đến chất lượng hoặc tính phù hợp của tất cả các khách sạn trên trang web của chúng tôi</p>
					<p>Chúng tôi bảo lưu quyền không chấp nhận các khách hàng hoặc các đặt phòng theo sự suy xét và quyết định riêng của chúng tôi và vì bất cứ lý do gì mà không cần phải chứng minh việc từ chối đó. Trong một vài trường hợp, chúng tôi có thể phải hủy hoặc từ chối việc đặt phòng do các sai sót hoặc nhầm lẫn trên trang web (ví dụ như nhầm lẫn về giá, về tên khách sạn, về ngày lưu trú, về tính phù hợp sẵn có của khách sạn). Trong những trường hợp này, số tiền khách hàng đã thanh toán cho Camnangdulich sẽ được hoàn trả lại mà không bị tính phí trong trường hợp đó. Lý do hủy bỏ hoặc từ chối đặt phòng trong các trường hợp này là theo sự xem xét và quyết định riêng của Camnangdulich</p>
					<p>Các nội dung đánh giá về khách sạn do khách hàng gửi cho Camnangdulich được xem là không có tính chất bảo mật và cũng không phải là thông tin sở hữu độc quyền. Camnangdulich không có bất kỳ trách nhiệm hoặc nghĩa vụ nào trong việc ghi nhận quyền tác giả cho người gửi.</p>
					<p>Camnangdulich không chịu trách nhiệm với bất kỳ sai sót, thiệt hại, mất mát nào do hỏng hóc máy móc từ máy chủ gây ra, vi rút xâm nhập, không kết nối được internet, thiên tai,…</p>
					<p>Nếu khách hàng đặt phòng hoặc sử dụng trang web cho một bên thứ ba (ví dụ như bạn, thành viên trong gia đình, cấp trên) thì khách hàng tự chịu trách nhiệm khi xảy ra bất kỳ sai sót nào về tính chính xác của các thông tin được cung cấp liên quan đến việc sử dung đó</p>
					<p>Chúng tôi luôn mong muốn giải quyết những đề xuất hoặc thắc mắc một cách nhanh chóng và công bằng. Mọi ý kiến đóng góp xin gửi về Bộ Phận Chăm Sóc Khách Hàng : Tầng 12, 242 Cống Quỳnh , quận 1 hoặc điện thoại : 08. 39251055 gửi qua địa chỉ&nbsp;email : info@Camnangdulich.com<br><br></p></span>
					</div>
				</div>
            <hr>
            <i class="fa fa-fw fa-map-marker ft-lh"></i><span>27 Nguyễn Tất Thành, Tân Lợi, Thành phố Buôn Ma Thuột, Đắk Lắk</span><br>
            <i class="fa fa-fw fa-phone ft-lh"></i><span>5003 555 678</span><br>
            <i class="fa fa-fw fa-envelope ft-lh"></i><span>camnangdulich360@gmail.com</span><br>
            <i class="fa fa-fw fa-facebook ft-lh"></i><span>camnangdulich@facebook.com</span>
        </div>
    </div>
    <!-- /.row -->
</div>