package entities;
// Generated Nov 27, 2017 2:56:12 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Chitiettin generated by hbm2java
 */
@Entity
@Table(name = "chitiettin", catalog = "db_dulich")
public class Chitiettin implements java.io.Serializable {

	private Integer idchitiettin;
	private Loaitin loaitin;
	private Tintuc tintuc;

	public Chitiettin() {
	}

	public Chitiettin(Loaitin loaitin, Tintuc tintuc) {
		this.loaitin = loaitin;
		this.tintuc = tintuc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idchitiettin", unique = true, nullable = false)
	public Integer getIdchitiettin() {
		return this.idchitiettin;
	}

	public void setIdchitiettin(Integer idchitiettin) {
		this.idchitiettin = idchitiettin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idloaitin", nullable = false)
	public Loaitin getLoaitin() {
		return this.loaitin;
	}

	public void setLoaitin(Loaitin loaitin) {
		this.loaitin = loaitin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtintuc", nullable = false)
	public Tintuc getTintuc() {
		return this.tintuc;
	}

	public void setTintuc(Tintuc tintuc) {
		this.tintuc = tintuc;
	}

}
