package entities;
// Generated Nov 24, 2017 4:52:57 PM by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Datphong generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "datphong", catalog = "db_dulich")
public class Datphong implements java.io.Serializable {

	private Integer iddatphong;
	private Loaiphong loaiphong;
	private Taikhoan taikhoan;
	private Trangthai trangthai;
	private Date ngaynhanphong;
	private Date ngaytraphong;
	private int soluongphong;
	private String hodem;
	private String ten;
	private String sodienthoai;
	private String email;

	public Datphong() {
	}

	public Datphong(Loaiphong loaiphong, Trangthai trangthai, Date ngaynhanphong, Date ngaytraphong, int soluongphong,
			String hodem, String ten, String sodienthoai, String email) {
		this.loaiphong = loaiphong;
		this.trangthai = trangthai;
		this.ngaynhanphong = ngaynhanphong;
		this.ngaytraphong = ngaytraphong;
		this.soluongphong = soluongphong;
		this.hodem = hodem;
		this.ten = ten;
		this.sodienthoai = sodienthoai;
		this.email = email;
	}

	public Datphong(Loaiphong loaiphong, Taikhoan taikhoan, Trangthai trangthai, Date ngaynhanphong, Date ngaytraphong,
			int soluongphong, String hodem, String ten, String sodienthoai, String email) {
		this.loaiphong = loaiphong;
		this.taikhoan = taikhoan;
		this.trangthai = trangthai;
		this.ngaynhanphong = ngaynhanphong;
		this.ngaytraphong = ngaytraphong;
		this.soluongphong = soluongphong;
		this.hodem = hodem;
		this.ten = ten;
		this.sodienthoai = sodienthoai;
		this.email = email;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "iddatphong", unique = true, nullable = false)
	public Integer getIddatphong() {
		return this.iddatphong;
	}

	public void setIddatphong(Integer iddatphong) {
		this.iddatphong = iddatphong;
	}

	@ManyToOne()
	@JoinColumn(name = "idloaiphong", nullable = false)
	public Loaiphong getLoaiphong() {
		return this.loaiphong;
	}

	public void setLoaiphong(Loaiphong loaiphong) {
		this.loaiphong = loaiphong;
	}

	@ManyToOne()
	@JoinColumn(name = "idtaikhoan")
	public Taikhoan getTaikhoan() {
		return this.taikhoan;
	}

	public void setTaikhoan(Taikhoan taikhoan) {
		this.taikhoan = taikhoan;
	}

	@ManyToOne()
	@JoinColumn(name = "idtrangthai", nullable = false)
	public Trangthai getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(Trangthai trangthai) {
		this.trangthai = trangthai;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngaynhanphong", nullable = false, length = 10)
	public Date getNgaynhanphong() {
		return this.ngaynhanphong;
	}

	public void setNgaynhanphong(Date ngaynhanphong) {
		this.ngaynhanphong = ngaynhanphong;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngaytraphong", nullable = false, length = 10)
	public Date getNgaytraphong() {
		return this.ngaytraphong;
	}

	public void setNgaytraphong(Date ngaytraphong) {
		this.ngaytraphong = ngaytraphong;
	}

	@Column(name = "soluongphong", nullable = false)
	public int getSoluongphong() {
		return this.soluongphong;
	}

	public void setSoluongphong(int soluongphong) {
		this.soluongphong = soluongphong;
	}

	@Column(name = "hodem", nullable = false, length = 50)
	public String getHodem() {
		return this.hodem;
	}

	public void setHodem(String hodem) {
		this.hodem = hodem;
	}

	@Column(name = "ten", nullable = false, length = 50)
	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	@Column(name = "sodienthoai", nullable = false, length = 11)
	public String getSodienthoai() {
		return this.sodienthoai;
	}

	public void setSodienthoai(String sodienthoai) {
		this.sodienthoai = sodienthoai;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
