package entities;
// Generated Nov 27, 2017 12:25:04 AM by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Dichvu generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "dichvu", catalog = "db_dulich", uniqueConstraints = { @UniqueConstraint(columnNames = "tendichvu"),
		@UniqueConstraint(columnNames = "slugurl") })
public class Dichvu implements java.io.Serializable {

	private Integer iddichvu;
	private String tendichvu;
	private String mota;
	private String slugurl;
	private Set<Khachsan> khachsans = new HashSet<Khachsan>(0);

	public Dichvu() {
	}

	public Dichvu(String tendichvu, String mota) {
		this.tendichvu = tendichvu;
		this.mota = mota;
	}
	
	public Dichvu(String tendichvu) {
		this.tendichvu = tendichvu;
	}

	public Dichvu(String tendichvu, String mota, String slugurl, Set<Khachsan> khachsans) {
		this.tendichvu = tendichvu;
		this.mota = mota;
		this.slugurl = slugurl;
		this.khachsans = khachsans;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "iddichvu", unique = true, nullable = false)
	public Integer getIddichvu() {
		return this.iddichvu;
	}

	public void setIddichvu(Integer iddichvu) {
		this.iddichvu = iddichvu;
	}

	@Column(name = "tendichvu", unique = true, nullable = false, length = 100)
	public String getTendichvu() {
		return this.tendichvu;
	}

	public void setTendichvu(String tendichvu) {
		this.tendichvu = tendichvu;
	}

	@Column(name = "mota", length = 65535)
	public String getMota() {
		return this.mota;
	}

	public void setMota(String mota) {
		this.mota = mota;
	}

	@Column(name = "slugurl", unique = true, length = 100)
	public String getSlugurl() {
		return this.slugurl;
	}

	public void setSlugurl(String slugurl) {
		this.slugurl = slugurl;
	}

	@ManyToMany( mappedBy = "dichvus")
	public Set<Khachsan> getKhachsans() {
		return this.khachsans;
	}

	public void setKhachsans(Set<Khachsan> khachsans) {
		this.khachsans = khachsans;
	}

}
