package entities;
// Generated Nov 27, 2017 2:56:12 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Loaiphong generated by hbm2java
 */
@Entity
@Table(name = "loaiphong", catalog = "db_dulich", uniqueConstraints = { @UniqueConstraint(columnNames = "tenloai"),
		@UniqueConstraint(columnNames = "slug") })
public class Loaiphong implements java.io.Serializable {

	private Integer idloaiphong;
	private Huong huong;
	private String tenloai;
	private String mota;
	private Boolean themgiuong;
	private String hinhanh;
	private int gia;
	private String slug;
	private Set<Datphong> datphongs = new HashSet<Datphong>(0);
	private Set<Chitietloaiphong> chitietloaiphongs = new HashSet<Chitietloaiphong>(0);

	public Loaiphong() {
	}

	public Loaiphong(String tenloai, String hinhanh, int gia) {
		this.tenloai = tenloai;
		this.hinhanh = hinhanh;
		this.gia = gia;
	}

	public Loaiphong(Huong huong, String tenloai, String mota, Boolean themgiuong, String hinhanh, int gia, String slug,
			Set<Datphong> datphongs, Set<Chitietloaiphong> chitietloaiphongs) {
		this.huong = huong;
		this.tenloai = tenloai;
		this.mota = mota;
		this.themgiuong = themgiuong;
		this.hinhanh = hinhanh;
		this.gia = gia;
		this.slug = slug;
		this.datphongs = datphongs;
		this.chitietloaiphongs = chitietloaiphongs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idloaiphong", unique = true, nullable = false)
	public Integer getIdloaiphong() {
		return this.idloaiphong;
	}

	public void setIdloaiphong(Integer idloaiphong) {
		this.idloaiphong = idloaiphong;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "huong")
	public Huong getHuong() {
		return this.huong;
	}

	public void setHuong(Huong huong) {
		this.huong = huong;
	}

	@Column(name = "tenloai", unique = true, nullable = false, length = 100)
	public String getTenloai() {
		return this.tenloai;
	}

	public void setTenloai(String tenloai) {
		this.tenloai = tenloai;
	}

	@Column(name = "mota", length = 65535)
	public String getMota() {
		return this.mota;
	}

	public void setMota(String mota) {
		this.mota = mota;
	}

	@Column(name = "themgiuong")
	public Boolean getThemgiuong() {
		return this.themgiuong;
	}

	public void setThemgiuong(Boolean themgiuong) {
		this.themgiuong = themgiuong;
	}

	@Column(name = "hinhanh", nullable = false, length = 250)
	public String getHinhanh() {
		return this.hinhanh;
	}

	public void setHinhanh(String hinhanh) {
		this.hinhanh = hinhanh;
	}

	@Column(name = "gia", nullable = false)
	public int getGia() {
		return this.gia;
	}

	public void setGia(int gia) {
		this.gia = gia;
	}

	@Column(name = "slug", unique = true, length = 100)
	public String getSlug() {
		return this.slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loaiphong")
	public Set<Datphong> getDatphongs() {
		return this.datphongs;
	}

	public void setDatphongs(Set<Datphong> datphongs) {
		this.datphongs = datphongs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loaiphong")
	public Set<Chitietloaiphong> getChitietloaiphongs() {
		return this.chitietloaiphongs;
	}

	public void setChitietloaiphongs(Set<Chitietloaiphong> chitietloaiphongs) {
		this.chitietloaiphongs = chitietloaiphongs;
	}

}
