package entities;
// Generated Nov 24, 2017 4:52:57 PM by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Loaitin generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "loaitin", catalog = "db_dulich", uniqueConstraints = @UniqueConstraint(columnNames = "loaitin") )
public class Loaitin implements java.io.Serializable {

	private Integer idloaitin;
	private String loaitin;
	private String mota;
	private Set<Chitiettin> chitiettins = new HashSet<Chitiettin>(0);

	public Loaitin() {
	}

	public Loaitin(String loaitin) {
		this.loaitin = loaitin;
	}

	public Loaitin(String loaitin, String mota, Set<Chitiettin> chitiettins) {
		this.loaitin = loaitin;
		this.mota = mota;
		this.chitiettins = chitiettins;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idloaitin", unique = true, nullable = false)
	public Integer getIdloaitin() {
		return this.idloaitin;
	}

	public void setIdloaitin(Integer idloaitin) {
		this.idloaitin = idloaitin;
	}

	@Column(name = "loaitin", unique = true, nullable = false, length = 100)
	public String getLoaitin() {
		return this.loaitin;
	}

	public void setLoaitin(String loaitin) {
		this.loaitin = loaitin;
	}

	@Column(name = "mota", length = 65535)
	public String getMota() {
		return this.mota;
	}

	public void setMota(String mota) {
		this.mota = mota;
	}

	@OneToMany( mappedBy = "loaitin")
	public Set<Chitiettin> getChitiettins() {
		return this.chitiettins;
	}

	public void setChitiettins(Set<Chitiettin> chitiettins) {
		this.chitiettins = chitiettins;
	}

}
