package entities;
// Generated Nov 24, 2017 2:13:28 AM by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Loaigiuong generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "loaigiuong", catalog = "db_dulich", uniqueConstraints = @UniqueConstraint(columnNames = "tenloaigiuong") )
public class Loaigiuong implements java.io.Serializable {

	private Integer idloaigiuong;
	private String tenloaigiuong;
	private String mota;
	private Set<Loaiphong> loaiphongs = new HashSet<Loaiphong>(0);

	public Loaigiuong() {
	}

	public Loaigiuong(String tenloaigiuong) {
		this.tenloaigiuong = tenloaigiuong;
	}

	public Loaigiuong(String tenloaigiuong, String mota, Set<Loaiphong> loaiphongs) {
		this.tenloaigiuong = tenloaigiuong;
		this.mota = mota;
		this.loaiphongs = loaiphongs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idloaigiuong", unique = true, nullable = false)
	public Integer getIdloaigiuong() {
		return this.idloaigiuong;
	}

	public void setIdloaigiuong(Integer idloaigiuong) {
		this.idloaigiuong = idloaigiuong;
	}

	@Column(name = "tenloaigiuong", unique = true, nullable = false, length = 45)
	public String getTenloaigiuong() {
		return this.tenloaigiuong;
	}

	public void setTenloaigiuong(String tenloaigiuong) {
		this.tenloaigiuong = tenloaigiuong;
	}

	@Column(name = "mota", length = 65535)
	public String getMota() {
		return this.mota;
	}

	public void setMota(String mota) {
		this.mota = mota;
	}

	@OneToMany( mappedBy = "loaigiuong")
	public Set<Loaiphong> getLoaiphongs() {
		return this.loaiphongs;
	}

	public void setLoaiphongs(Set<Loaiphong> loaiphongs) {
		this.loaiphongs = loaiphongs;
	}

}
