package entities;
// Generated Nov 24, 2017 2:13:28 AM by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Phanhoi generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "phanhoi", catalog = "db_dulich")
public class Phanhoi implements java.io.Serializable {

	private Integer idphanhoi;
	private Taikhoan taikhoan;
	private String hovaten;
	private String email;
	private String noidung;

	public Phanhoi() {
	}

	public Phanhoi(String hovaten, String email, String noidung) {
		this.hovaten = hovaten;
		this.email = email;
		this.noidung = noidung;
	}

	public Phanhoi(Taikhoan taikhoan, String hovaten, String email, String noidung) {
		this.taikhoan = taikhoan;
		this.hovaten = hovaten;
		this.email = email;
		this.noidung = noidung;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idphanhoi", unique = true, nullable = false)
	public Integer getIdphanhoi() {
		return this.idphanhoi;
	}

	public void setIdphanhoi(Integer idphanhoi) {
		this.idphanhoi = idphanhoi;
	}

	@ManyToOne()
	@JoinColumn(name = "idtaikhoan")
	public Taikhoan getTaikhoan() {
		return this.taikhoan;
	}

	public void setTaikhoan(Taikhoan taikhoan) {
		this.taikhoan = taikhoan;
	}

	@Column(name = "hovaten", nullable = false, length = 100)
	public String getHovaten() {
		return this.hovaten;
	}

	public void setHovaten(String hovaten) {
		this.hovaten = hovaten;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "noidung", nullable = false, length = 65535)
	public String getNoidung() {
		return this.noidung;
	}

	public void setNoidung(String noidung) {
		this.noidung = noidung;
	}

}
