package entities;
// Generated Dec 2, 2017 7:44:26 PM by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Taikhoan generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "taikhoan", catalog = "db_dulich", uniqueConstraints = { @UniqueConstraint(columnNames = "email"),
		@UniqueConstraint(columnNames = "sodienthoai"), @UniqueConstraint(columnNames = "sluglink"),
		@UniqueConstraint(columnNames = "keypass") })
public class Taikhoan implements java.io.Serializable {

	private Integer idtaikhoan;
	private Quyen quyen;
	private Trangthai trangthai;
	private String email;
	private String matkhau;
	private String hodem;
	private String ten;
	private String sodienthoai;
	private String diachi;
	private String avatar;
	private Date ngaytao;
	private String sluglink;
	private String keypass;
	private Set<Tintuc> tintucs = new HashSet<Tintuc>(0);
	private Set<Khachsan> khachsans = new HashSet<Khachsan>(0);
	private Set<Phanhoi> phanhois = new HashSet<Phanhoi>(0);
	private Set<Datphong> datphongs = new HashSet<Datphong>(0);
	private Set<Dattour> dattours = new HashSet<Dattour>(0);
	private Set<Congty> congties = new HashSet<Congty>(0);
	private Set<Danhgia> danhgias = new HashSet<Danhgia>(0);

	public Taikhoan() {
	}
	
	public Taikhoan(String email, String matkhau, String sodienthoai, String hodem, String ten, String avatar, Date ngaytao, Quyen quyen,
			Trangthai trangthai) {
		this.email = email;
		this.matkhau = matkhau;
		this.sodienthoai = sodienthoai;
		this.hodem = hodem;
		this.ten = ten;
		this.avatar = avatar;
		this.ngaytao = ngaytao;
		this.quyen = quyen;
		this.trangthai = trangthai;
	}
	
	public Taikhoan(String email, String matkhau, String sodienthoai, String hodem, String ten, String avatar, Date ngaytao, Quyen quyen,
			Trangthai trangthai, String keypass) {
		this.email = email;
		this.matkhau = matkhau;
		this.sodienthoai = sodienthoai;
		this.hodem = hodem;
		this.ten = ten;
		this.avatar = avatar;
		this.ngaytao = ngaytao;
		this.quyen = quyen;
		this.trangthai = trangthai;
		this.keypass = keypass;
	}

	public Taikhoan(Quyen quyen, Trangthai trangthai, String email, String matkhau, String sodienthoai) {
		this.quyen = quyen;
		this.trangthai = trangthai;
		this.email = email;
		this.matkhau = matkhau;
		this.sodienthoai = sodienthoai;
	}

	public Taikhoan(Quyen quyen, Trangthai trangthai, String email, String matkhau, String hodem, String ten,
			String sodienthoai, String diachi, String avatar, Date ngaytao, String sluglink, String keypass,
			Set<Tintuc> tintucs, Set<Khachsan> khachsans, Set<Phanhoi> phanhois, Set<Datphong> datphongs,
			Set<Dattour> dattours, Set<Congty> congties, Set<Danhgia> danhgias) {
		this.quyen = quyen;
		this.trangthai = trangthai;
		this.email = email;
		this.matkhau = matkhau;
		this.hodem = hodem;
		this.ten = ten;
		this.sodienthoai = sodienthoai;
		this.diachi = diachi;
		this.avatar = avatar;
		this.ngaytao = ngaytao;
		this.sluglink = sluglink;
		this.keypass = keypass;
		this.tintucs = tintucs;
		this.khachsans = khachsans;
		this.phanhois = phanhois;
		this.datphongs = datphongs;
		this.dattours = dattours;
		this.congties = congties;
		this.danhgias = danhgias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idtaikhoan", unique = true, nullable = false)
	public Integer getIdtaikhoan() {
		return this.idtaikhoan;
	}

	public void setIdtaikhoan(Integer idtaikhoan) {
		this.idtaikhoan = idtaikhoan;
	}

	@ManyToOne()
	@JoinColumn(name = "idquyen", nullable = false)
	public Quyen getQuyen() {
		return this.quyen;
	}

	public void setQuyen(Quyen quyen) {
		this.quyen = quyen;
	}

	@ManyToOne()
	@JoinColumn(name = "idtrangthai", nullable = false)
	public Trangthai getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(Trangthai trangthai) {
		this.trangthai = trangthai;
	}

	@Column(name = "email", unique = true, nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "matkhau", nullable = false, length = 100)
	public String getMatkhau() {
		return this.matkhau;
	}

	public void setMatkhau(String matkhau) {
		this.matkhau = matkhau;
	}

	@Column(name = "hodem", length = 50)
	public String getHodem() {
		return this.hodem;
	}

	public void setHodem(String hodem) {
		this.hodem = hodem;
	}

	@Column(name = "ten", length = 50)
	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	@Column(name = "sodienthoai", unique = true, nullable = false, length = 11)
	public String getSodienthoai() {
		return this.sodienthoai;
	}

	public void setSodienthoai(String sodienthoai) {
		this.sodienthoai = sodienthoai;
	}

	@Column(name = "diachi", length = 250)
	public String getDiachi() {
		return this.diachi;
	}

	public void setDiachi(String diachi) {
		this.diachi = diachi;
	}

	@Column(name = "avatar", length = 250)
	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ngaytao", length = 19)
	public Date getNgaytao() {
		return this.ngaytao;
	}

	public void setNgaytao(Date ngaytao) {
		this.ngaytao = ngaytao;
	}

	@Column(name = "sluglink", unique = true, length = 100)
	public String getSluglink() {
		return this.sluglink;
	}

	public void setSluglink(String sluglink) {
		this.sluglink = sluglink;
	}

	@Column(name = "keypass", unique = true, length = 250)
	public String getKeypass() {
		return this.keypass;
	}

	public void setKeypass(String keypass) {
		this.keypass = keypass;
	}

	@OneToMany(mappedBy = "taikhoan")
	public Set<Tintuc> getTintucs() {
		return this.tintucs;
	}

	public void setTintucs(Set<Tintuc> tintucs) {
		this.tintucs = tintucs;
	}

	@OneToMany(mappedBy = "taikhoan")
	public Set<Khachsan> getKhachsans() {
		return this.khachsans;
	}

	public void setKhachsans(Set<Khachsan> khachsans) {
		this.khachsans = khachsans;
	}

	@OneToMany(mappedBy = "taikhoan")
	public Set<Phanhoi> getPhanhois() {
		return this.phanhois;
	}

	public void setPhanhois(Set<Phanhoi> phanhois) {
		this.phanhois = phanhois;
	}

	@OneToMany(mappedBy = "taikhoan")
	public Set<Datphong> getDatphongs() {
		return this.datphongs;
	}

	public void setDatphongs(Set<Datphong> datphongs) {
		this.datphongs = datphongs;
	}

	@OneToMany(mappedBy = "taikhoan")
	public Set<Dattour> getDattours() {
		return this.dattours;
	}

	public void setDattours(Set<Dattour> dattours) {
		this.dattours = dattours;
	}

	@OneToMany(mappedBy = "taikhoan")
	public Set<Congty> getCongties() {
		return this.congties;
	}

	public void setCongties(Set<Congty> congties) {
		this.congties = congties;
	}

	@OneToMany(mappedBy = "taikhoan")
	public Set<Danhgia> getDanhgias() {
		return this.danhgias;
	}

	public void setDanhgias(Set<Danhgia> danhgias) {
		this.danhgias = danhgias;
	}

}
