package entities;
// Generated Nov 27, 2017 12:25:04 AM by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Trangthai generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "trangthai", catalog = "db_dulich", uniqueConstraints = @UniqueConstraint(columnNames = "trangthai") )
public class Trangthai implements java.io.Serializable {

	private Integer idtrangthai;
	private String trangthai;
	private String mota;
	private Set<Tintuc> tintucs = new HashSet<Tintuc>(0);
	private Set<Tour> tours = new HashSet<Tour>(0);
	private Set<Congty> congties = new HashSet<Congty>(0);
	private Set<Datphong> datphongs = new HashSet<Datphong>(0);
	private Set<Khachsan> khachsans = new HashSet<Khachsan>(0);
	private Set<Taikhoan> taikhoans = new HashSet<Taikhoan>(0);
	private Set<Dattour> dattours = new HashSet<Dattour>(0);

	public Trangthai() {
	}

	public Trangthai(String trangthai) {
		this.trangthai = trangthai;
	}

	public Trangthai(String trangthai, String mota, Set<Tintuc> tintucs, Set<Tour> tours, Set<Congty> congties,
			Set<Datphong> datphongs, Set<Khachsan> khachsans, Set<Taikhoan> taikhoans, Set<Dattour> dattours) {
		this.trangthai = trangthai;
		this.mota = mota;
		this.tintucs = tintucs;
		this.tours = tours;
		this.congties = congties;
		this.datphongs = datphongs;
		this.khachsans = khachsans;
		this.taikhoans = taikhoans;
		this.dattours = dattours;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idtrangthai", unique = true, nullable = false)
	public Integer getIdtrangthai() {
		return this.idtrangthai;
	}

	public void setIdtrangthai(Integer idtrangthai) {
		this.idtrangthai = idtrangthai;
	}

	@Column(name = "trangthai", unique = true, nullable = false, length = 50)
	public String getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(String trangthai) {
		this.trangthai = trangthai;
	}

	@Column(name = "mota", length = 65535)
	public String getMota() {
		return this.mota;
	}

	public void setMota(String mota) {
		this.mota = mota;
	}

	@OneToMany( mappedBy = "trangthai")
	public Set<Tintuc> getTintucs() {
		return this.tintucs;
	}

	public void setTintucs(Set<Tintuc> tintucs) {
		this.tintucs = tintucs;
	}

	@OneToMany( mappedBy = "trangthai")
	public Set<Tour> getTours() {
		return this.tours;
	}

	public void setTours(Set<Tour> tours) {
		this.tours = tours;
	}

	@OneToMany( mappedBy = "trangthai")
	public Set<Congty> getCongties() {
		return this.congties;
	}

	public void setCongties(Set<Congty> congties) {
		this.congties = congties;
	}

	@OneToMany( mappedBy = "trangthai")
	public Set<Datphong> getDatphongs() {
		return this.datphongs;
	}

	public void setDatphongs(Set<Datphong> datphongs) {
		this.datphongs = datphongs;
	}

	@OneToMany( mappedBy = "trangthai")
	public Set<Khachsan> getKhachsans() {
		return this.khachsans;
	}

	public void setKhachsans(Set<Khachsan> khachsans) {
		this.khachsans = khachsans;
	}

	@OneToMany( mappedBy = "trangthai")
	public Set<Taikhoan> getTaikhoans() {
		return this.taikhoans;
	}

	public void setTaikhoans(Set<Taikhoan> taikhoans) {
		this.taikhoans = taikhoans;
	}

	@OneToMany( mappedBy = "trangthai")
	public Set<Dattour> getDattours() {
		return this.dattours;
	}

	public void setDattours(Set<Dattour> dattours) {
		this.dattours = dattours;
	}

}
